### ISSUE TITLE
Clean run without weights

### ISSUE THREAD

**Issue by lauken13** [lauken13/mrpkit#114]
Need to rerun the full workflow without weights specified. @jgabry noted there's an issue in tabulate.

**Comment by lauken13** [comment]
Hey @jgabry, I've tried to replicate this in a bunch of different ways but can't. If weights are specified we currently assign a weight of 1 so there are no problems in tabulate. I've added in an extra warning and doc about this on the bug-fixes2 branch. I'm happy to investigate further, could you see if you can reproduce the error with the current main branch?

**Comment by jgabry** [comment]
Thanks, yeah I'll give this a try and let you know. It's possible that the
errors were happening on an outdated branch or something.

**Comment by jgabry** [comment]
Seems like it's working now!
