### ISSUE TITLE
Helper function to extract munged data

### ISSUE THREAD

**Issue by lauken13** [lauken13/mrpkit#119]
Suggest  a helper function to assist extracting:

- munged survey data
- weighted estimates

**Comment by jgabry** [comment]
> * munged survey data

Do you mean the data frame created when `mapping()` is called? We currently have methods 

* `SurveyMap$mapped_sample_data()`
* `SurveyMap$mapped_population_data()`

Or were you thinking of extracting different data? Either way I agree we should have methods for extracting all the useful data. 

> * weighted estimates

Yeah this seems useful

**Comment by lauken13** [comment]
The first two are perfect! I realise the weighted estimates we would need to change the place we calculate them -  see #121

**Comment by jgabry** [comment]
closing because we have this now
