### ISSUE TITLE
Weights in aggregate or plot

### ISSUE THREAD

**Issue by lauken13** [lauken13/mrpkit#121]
Currently we calculate weighted estimates  in the plot function to included on figures. I wonder if it would be better to do this in the aggregate function and return a list of two - mrp estimate and wtd estmate?

**Comment by lauken13** [comment]
Suggest returning a dataframe with an extra column "wtd_est" or similar.

**Comment by lauken13** [comment]
Hey @jgabry, @RohanAlexander & @Dewi-Amaliah,

We talked in the meeting about adding an extra column "wtd_est" and "wtd_std". However the aggregate function returns a dataframe of dimension (n_levels_in_by X n_samples) by 2 or 1, which means we'd be working kind of a weird form. 

What about changing the data frame so it has columns : age (or nothing for popn estimates), value, type; where type is either posterior_draw OR wtd_est OR wtd_std as necessary. That way if weights are included it wouldn't change the overall number of columns, just add a couple of rows.

**Comment by lauken13** [comment]
I think it would be preferable to have a list of length 2, but I can also understand why you wouldn't want that and this is the only other way I can think of doing it. 

As proposed it would be something like

group estimate type
18-25 a number posterior
18-25 a number posterior
...number of posterior samples
18-25 a number posterior
18-25 a number wtd_mean
18-25 a number wtd_se

What do you think?
etc. for all groups w/o 1st column for the population estimate.

**Comment by jgabry** [comment]
> I think it would be preferable to have a list of length 2, but I can also understand why you wouldn't want that and this is the only other way I can think of doing it.

Yeah I don't love the list idea but I think you might be right that it's the best option. Will think about it more today.

**Comment by lauken13** [comment]
Suggest a named_list list of three (always)

- 1: posterior draws
- 2: raw_data estimates
- 3: wtd_estimates (if applicable NULL if not)

Names??? mrp_estimate, raw_estimate, wtd_estimate?

ORRRRR

aggregate returns what it does, but add another method which calculates a summary

Method name: summary? 

group mean se method
18-25 number number "mrp"
18-25 number number "wtd"
18-25 number number "raw"
