### ISSUE TITLE
Refactor to rely on dplyr

### ISSUE THREAD

**Issue by lauken13** [lauken13/mrpkit#134]
The code currently uses:

- dplyr
- forloops
- base r

to summarise over groups. Propose moving to dplyr as discussed in our meeting the week for easier maintenance.

**Comment by jgabry** [comment]
Sounds good!

**Comment by jgabry** [comment]
When using dplyr in a CRAN package we need to use special syntax to avoid R CMD check notes: https://dplyr.tidyverse.org/articles/programming.html#eliminating-r-cmd-check-notes-1, e.g., instead of `group_by(age)` use `group_by(.data$age)`

**Comment by jgabry** [comment]
This was partially addressed by #137 but will leave it open until we decide about whether to convert other code to dplyr too. I think the main one to decide on is the code from aggregate() that @lauken13 mentioned needed to be profiled: 

> Potentially a case in aggregate, but this is computationally slow. Currently uses apply + for loops and is pretty efficient. Recommend we wait until someone has time to profile.
