### ISSUE TITLE
Need to test custom modeling functions

### ISSUE THREAD

**Issue by lauken13** [lauken13/mrpkit#144]
- Using rstan + custom function for predict
- INLA - still has model formula but is quite different

**Comment by jgabry** [comment]
Right now we're requiring a `formula` argument to the modeling function, which will limit the custom options. We can look into relaxing that requirement.

**Comment by jgabry** [comment]
Actually, just noticed we have an issue open related to my comment above: #105

**Comment by lauken13** [comment]
I think we will need to alway assume a formula argument because we intrinsically always need to know what variables are the outcome and which are the predictors? 
Do you have an example of a non-formula based algorithm so we can think it through?

**Comment by jgabry** [comment]
> Do you have an example of a non-formula based algorithm so we can think it through?

How about a function that calls RStan or CmdStanR to run a Stan program but not via rstanarm or brms?

**Comment by lauken13** [comment]
I am closing this issue for duplication but have mentioned it over in the other issue
