### ISSUE TITLE
Delete "sandbox" and "paper" folders?

### ISSUE THREAD

**Issue by jgabry** [lauken13/mrpkit#151]
@lauken13 I think we can safely delete the "sandbox" and "paper" folders from the repository (both are outdated and not used anymore), but just wanted to double check here before doing it.

**Comment by lauken13** [comment]
Sounds good. I have done now in [4c1a717](https://github.com/lauken13/mrpkit/commit/4c1a717836cc009ec5f3477a64c538970c0d71b0)

Didn't bother making a PR
