### ISSUE TITLE
Bug in mapping

### ISSUE THREAD

**Issue by kinto-b** [lauken13/mrpkit#153]
Hi there,

I am not sure what is causing this issue, but I suspect it is due to the sample and population already having the same levels.

(As a sidenote, it would be useful to have a shorthand to specify that the levels are identical).

``` r
lga_names <- c(
    "Central Coast (NSW)",
    "Murray River",
    "Port Macquarie-Hastings",
    "Logan",
    "Newcastle",
    "Tamworth",
    "Busselton"
  )

dat <- mrpkit::SurveyData$new(data=data.frame(
  lga = sample(lga_names, 1000, TRUE),
  y = rnorm(1000)
))
#> Warning: No 'questions' and 'responses' provided. Using all factor, character,
#> and binary variables in 'data' by default.
#> Warning: 'Weights have not been provided, assume all data weighted with weight
#> 1.


pop <- data.frame(
  lga = lga_names,
  n = runif(length(lga_names), 100, 10000)
)
pop <- pop[pop$lga %in% dat$responses()$lga, ]
pop <- mrpkit::SurveyData$new(data = pop, weights = "n")
#> Warning: No 'questions' and 'responses' provided. Using all factor, character,
#> and binary variables in 'data' by default.



mapper <- mrpkit::SurveyMap$new(
  dat, pop, 
  mrpkit::QuestionMap$new(
    "lga", 
    c("lga", "lga"), 
    `names<-`(as.list(dat$responses()$lga), dat$responses()$lga) # Map names to themselves
  )
)
#> Warning: Converting 'lga' into a factor with levels Busselton, Central Coast
#> (NSW), Logan, Murray River, Newcastle, Port Macquarie-Hastings, Tamworth
#> Warning: Converting 'lga' into a factor with levels Busselton, Central Coast
#> (NSW), Logan, Murray River, Newcastle, Port Macquarie-Hastings, Tamworth

mapper$mapping()
#> Error in new_levels_samp_names[samp_level] <- row.names(mapped_levels_fin)[grep(levels_samp[samp_level], : replacement has length zero
```

<sup>Created on 2023-07-21 with [reprex v2.0.2](https://reprex.tidyverse.org)</sup>

**Comment by lauken13** [comment]
Hi!

Thanks for the suggestion and for letting us know about the error. I'll take a look first thing tomorrow and get back to you afterwards. :)

**Comment by lauken13** [comment]
So I think the issues is to do with grep requiring fixed = TRUE explicitly. I've made a PR #157 to fix.

The idea of adding a shortcut for the same levels is great though, we should think about what that would look like!

**Comment by kinto-b** [comment]
Great to hear :) 

Could the values map be made an optional argument? Then, e.g.,

```r
lga_map <- mrpkit::QuestionMap$new("lga", c("lga", "lga"))
```

would assume the levels are identical?

Could you do something similar for variable names that match so that you don't have to write the name twice? So:

```r
lga_map <- mrpkit::QuestionMap$new("lga", "lga")
```

Going one step even futher, if the colnames are optional too, then we assume both columns have the same name as the question map. So in our instance:

```r
lga_map <- mrpkit::QuestionMap$new("lga")
```

**Comment by lauken13** [comment]
That's a great idea. Opening in a separate issue and closing this as the bug has been resolved
