### ISSUE TITLE
Check resilience to multiple lhs vars

### ISSUE THREAD

**Issue by lauken13** [lauken13/mrpkit#155]
Following up from #150 

Line 184 of Survey fit
`          dplyr::select(dplyr::all_of(lhs_var), .key)%>%`

Need to check performance with multiple LHS vars (like when using brms y_count|trials(n))

**Comment by jgabry** [comment]
I realized that the problem with binomial models may go deeper than this unfortunately (see https://github.com/lauken13/mrpkit/issues/156). And I may have only found a subset of the issues.

**Comment by lauken13** [comment]
Yeah it would be all through. Can you think of a good way to get around it?

**Comment by jgabry** [comment]
I'll think about it and let's talk about it more at the next meeting. We might need to brainstorm.

**Comment by jgabry** [comment]
See #156 instead
