### ISSUE TITLE
Host repo

### ISSUE THREAD

**Issue by lauken13** [lauken13/mrpkit#44]
Jonah wants to maintain the history if possible

Concerns:
- none for CRAN
- Appearances
- Person who owns the account can delete the repo
- We can't access the settings, but we can continue to develop

@mitzimorris

**Comment by jgabry** [comment]
@mitzimorris Can you rename the repo to "mrpkit" instead of "mrp-kit" so it matches the package name? I think you're the only one who can edit the repo name.
