### ISSUE TITLE
 aggregate returns `draw` column only if `by` is specified

### ISSUE THREAD

**Issue by jgabry** [lauken13/mrpkit#66]
Right now if `by` is specified then the data frame returned by `aggregate` has a column `draw`, which basically just serves to indicate that the rows correspond to different posterior draws. However, this column is not included if `by` isn't specified. Is that what we want? 

This feels like a bug to me. I think we should either always include `draw` (I'm not sure why it should be conditional on specifying `by`) or never include it (it doesn't seem to be used for anything). 

Opinions on this?

**Comment by jgabry** [comment]
Main reason in favor of dropping `draw` column: it provides no information. 

Main reason in favor of keeping `draw` column: it may be useful for reshaping from long to wide for various post-processing purposes. 

If we do end up keeping it then we should also add it to the output when `by` isn't specified for consistency.

**Comment by jgabry** [comment]
Ok I tested it out and @lauken13 is 100% right that it's way easier to reshape from long to wide if we have a `draw` column (it's just one line of code whereas without it we need a few more to recreate it): 

```r
estimates_by_age <- fit_1$aggregate(poststrat_estimates, by = "age")
tidyr::pivot_wider(estimates_by_age, names_from = "draw")

# A tibble: 4 x 6
  age     `1`   `2`   `3`   `4`   `5`
  <fct> <dbl> <dbl> <dbl> <dbl> <dbl>
1 18-35 0.635 0.764 0.490 0.477 0.600
2 36-55 0.725 0.730 0.771 0.750 0.785
3 56-65 0.751 0.749 0.762 0.742 0.779
4 66+   0.715 0.683 0.681 0.661 0.680
```

(There are only 5 draws in this toy example, so only 5 columns, but there would typically be thousands.)

But looking at this reshaped object I'm not sure what it would be useful for with the _draws_ as columns like this. Unlike what I hinted at earlier in our conversation this isn't  actually something that bayesplot could do anything with (I was imagining something different) and I'm not sure what else would be done with it that wouldn't be easier done using in long format. It seems to me that we would want to compute things by age category but not by draw, and computing by age category would be easier in long form, e.g., 

```r
estimates_by_age %>% group_by(age) %>% etc.
```

But I could easily be overlooking one or many things. Am I missing something that we'd want to do using this reshaped object?

**Comment by lauken13** [comment]
@Dewi-Amaliah suggested that we don't show the draw in the beta release and see how people go. I still feel like it's a bit weird without it, but I can't think of an actual use case for it.

**Comment by jgabry** [comment]
I like @Dewi-Amaliah's idea. We can definitely add the column if a use case arises. But I'm also ok with keeping it if you feel strongly about it (if we do that we should just also add it when `by` isn't specified). 

Also, whether we keep it or wait to add it later, I think we should call it `.draw` instead of `draw` to indicate it's metadata. This would be consistent with certain practices in the tidyverse and various other packages.

**Comment by lauken13** [comment]
For beta testing, we will remove draw

**Comment by Dewi-Amaliah** [comment]
Hi @lauken13 and @jgabry,

Since we will remove draw in beta testing,  are line [140-142](https://github.com/mitzimorris/mrp-kit/blob/master/R/SurveyMap.R) still needed?

**Comment by lauken13** [comment]
I don't think so, @jgabry?

**Comment by jgabry** [comment]
Do you mean these lines in the examples section? 

```r
#' estimates_by_age %>%
#'   group_by(age) %>%
#'   summarize(mean = mean(value), sd = sd(value))
```

I think we can keep those lines in the examples even if we remove `draw` because it's grouping by `age` not `draw`. Or am I misunderstanding the issue?

**Comment by Dewi-Amaliah** [comment]
Yes, those lines, and it would be group by `age`. However, it will summarise `mean` and `sd` of `age` based on `draw`, right? Or, another variable?

**Comment by jgabry** [comment]
> However, it will summarise `mean` and `sd` of `age` based on `draw`, right?

In this example we're not summarizing `draw` or grouping by `draw`, so `draw` isn't used at all. It will summarize the mean and sd of `value` based on `age` and the answer is the same regardless of whether `draw` is included: 

```r
# includes 'draw' column
head(estimates_by_age) 
    age draw     value
1 18-35    1 0.7584347
2 36-55    1 0.7567402
3 56-65    1 0.7712137
4   66+    1 0.7644404
5 18-35    2 0.7344509
6 36-55    2 0.7304963

> estimates_by_age %>% group_by(age) %>% summarize(mean = mean(value), sd = sd(value))
# A tibble: 4 x 3
  age    mean     sd
  <fct> <dbl>  <dbl>
1 18-35 0.707 0.0616
2 36-55 0.762 0.0308
3 56-65 0.753 0.0279
4 66+   0.731 0.0334
   
# we get the same answer if we remove 'draw'
estimates_by_age$draw <- NULL
estimates_by_age %>% group_by(age) %>% summarize(mean = mean(value), sd = sd(value))
# A tibble: 4 x 3
  age    mean     sd
  <fct> <dbl>  <dbl>
1 18-35 0.707 0.0616
2 36-55 0.762 0.0308
3 56-65 0.753 0.0279
4 66+   0.731 0.0334
```
