### ISSUE TITLE
Use GitHub Actions for CI

### ISSUE THREAD

**Issue by jgabry** [lauken13/mrpkit#76]
Implement continuous integration (CI) using GitHub Actions. At a minimum this should include doing the following automatically for the master branch and every time there is a pull request: 

* Running R CMD check (i.e. CRAN checks and tests) on both R-release and R-devel and on Windows, Mac, and Linux
* Running test coverage checks and uploading to codecov

**Comment by lauken13** [comment]
Do we want to use rstan or cmdstanr as a backend for brms?
Don't want to set a dependency in the test file (forces a dependency)

**Comment by jgabry** [comment]
@mitzimorris Can you enable codecov for the repo?

**Comment by jgabry** [comment]
closing because we have this now
